FILE=tutorial

make:
	texi2pdf $(FILE).tex

clean:
	rm -f $(FILE).log $(FILE).out $(FILE).pdf $(FILE).toc $(FILE).aux
	rm -f $(FILE).bbl $(FILE).blg $(FILE).brf $(FILE).nav $(FILE).snm
	rm -f $(FILE)-blx.bib $(FILE).vrb $(FILE).run.xml
